// Streams a compact, one-event-per-line report of a headless auto-played campaign to docs/ai-run.md.  All the
// simulation lives in the pure, unit-tested src/game/auto-play engine (it runs the real GameWorld at a fixed 60fps
// and buys the cheapest affordable upgrade / unlock between every step); this wrapper only formats each event it
// emits into a line and writes it out as it arrives, so a long run can be scanned while it is still running.
//
// Run with `npm run report:ai-run`.  Pass an output path to write somewhere other than docs/ai-run.md.
import { openSync, writeSync, closeSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { autoPlay, DEFAULT_MAX_DEATHS_PER_LEVEL, type AutoPlayEvent, type AutoPlayEndReason } from '@/game/auto-play';

// A cumulative game-time prefix (across every level and retry), right-aligned so the events line up in a column.
function at(totalMs: number): string {
	return `${(totalMs / 1000).toFixed(1).padStart(6)}s`;
}

function seconds(ms: number): string {
	return `${(ms / 1000).toFixed(1)}s`;
}

const END_MESSAGES: Record<AutoPlayEndReason, string> = {
	'campaign-cleared': 'cleared every level - campaign complete.',
	'deaths-exceeded': `died more than ${DEFAULT_MAX_DEATHS_PER_LEVEL} times on a single level before prestige - stopping.`,
	'prestige-stalled': 'a Singularity could not push past the previous run - stopping.',
	'stalled': 'a level never resolved - stopping.',
	'no-player': 'level had no player station - stopping.',
};

// Dark Matter carried into a level, shown only once a prestige has banked some (a fresh, pre-prestige run has none).
function dm(darkMatter: number): string {
	return darkMatter > 0 ? `  DM ${darkMatter}` : '';
}

// Formats one engine event into its report line.  Every event type produces a line.
function formatEvent(event: AutoPlayEvent): string {
	switch(event.type) {
		case 'level-start':
			return `${at(event.totalMs)}  --- LEVEL ${event.levelIndex + 1} ${event.level.name} "${event.level.title}"  ` +
				`start $${event.state.money}  [${event.state.summary}]`;
		case 'buy':
			return `${at(event.totalMs)}  BUY ${event.action.kind.padEnd(6)} ${event.action.type.padEnd(14)} ` +
				`$${event.action.cost}  (now r${event.rate}/l${event.level}, $${event.moneyLeft} left)`;
		case 'win':
			return `${at(event.totalMs)}  WIN ${event.level.name} "${event.level.title}"  ${seconds(event.levelMs)} on level  ` +
				`$${event.state.money}  [${event.state.summary}]${dm(event.darkMatter)}`;
		case 'die':
			return `${at(event.totalMs)}  DIE ${event.level.name} "${event.level.title}"  ${seconds(event.levelMs)} on level  ` +
				`$${event.state.money}  [${event.state.summary}]  death ${event.deaths}/${DEFAULT_MAX_DEATHS_PER_LEVEL}${dm(event.darkMatter)}`;
		case 'prestige':
			return `${at(event.totalMs)}  *** PRESTIGE peak level ${event.highestLevelIndex + 1}  banked ${event.banked} Dark Matter  ` +
				`(${event.darkMatter} total) - entering the Singularity`;
		case 'buy-node':
			return `${at(event.totalMs)}  NODE ${event.id.padEnd(14)} -> level ${event.nodeLevel}  ` +
				`${event.cost} DM  (${event.darkMatterLeft} DM left)`;
		case 'stall':
			return `${at(event.totalMs)}  STALL ${event.level.name} unresolved after ${seconds(event.levelMs)} of play.`;
		case 'end':
			return `${at(event.totalMs)}  END ${END_MESSAGES[event.reason]}`;
		default:
			// Every event type is handled above; this keeps the switch exhaustive if a new one is added.
			return event satisfies never;
	}
}

async function main(): Promise<void> {
	const outArg = process.argv[2];
	const outPath = outArg ?? fileURLToPath(new URL('../docs/ai-run.md', import.meta.url));
	const fd = openSync(outPath, 'w');
	const write = (line: string) => writeSync(fd, line + '\n');

	write('# AI Run');
	write('');
	write(
		'_Greedy auto-player: runs the real simulation at a fixed 1/60s step and, between every step, buys the ' +
		'single cheapest upgrade or ship unlock it can afford. Generated by `npm run report:ai-run`._',
	);
	write('');
	write('Each line starts with the total game time since the run began. `BUY` is one purchase; `WIN` / `DIE` end');
	write('a level with the time spent on it, the money in hand, and each built type as `rate/level`.');
	write('');
	write('After more than 5 deaths on one level (once prestige is unlocked), the run collapses into a Singularity:');
	write('a `*** PRESTIGE` line banks Dark Matter for the peak reached, `NODE` lines show the Ascendancy nodes it then');
	write('buys, and the run restarts from level 1 with those bonuses. `DM n` on a `WIN`/`DIE` is the Dark Matter in hand.');
	write('');

	for await (const event of autoPlay()) {
		write(formatEvent(event));
	}

	closeSync(fd);
	process.stderr.write(`\nWrote ${outPath}\n`);
}

await main();
